/**
 * meteor-jade-loader
 *
 * A Rspack/webpack loader that compiles Meteor .jade template files into
 * JavaScript that registers Blaze templates via the Meteor Package globals.
 *
 * Usage in rspack/webpack config:
 *   {
 *     test: /\.jade$/,
 *     use: [{ loader: 'meteor-jade-loader' }],
 *   }
 *
 * Output is JavaScript that uses the Meteor Package globals (Template, HTML,
 * Blaze, Spacebars) which must be available at runtime.
 */

'use strict';

import path from 'path';
import getCompiler from './lib/jade-compiler';
import { HtmlContent, JadeFileResult } from './lib/types';

/**
 * The subset of the webpack/rspack loader context this loader relies on.
 */
interface LoaderContext {
  resourcePath?: string;
  emitError(error: Error): void;
}

/**
 * Generate the JS code for a single template registration.
 */
function generateTemplateJS(name: string, renderFuncCode: string): string {
  const nameLiteral = JSON.stringify(name);
  const templateDotNameLiteral = JSON.stringify('Template.' + name);

  return (
    'Template.__checkName(' + nameLiteral + ');\n' +
    'Template[' + nameLiteral + '] = new Template(' + templateDotNameLiteral + ', ' + renderFuncCode + ');\n'
  );
}

/**
 * Generate the JS code for the body content.
 */
function generateBodyJS(renderFuncCode: string): string {
  return (
    'Template.body.addContent(' + renderFuncCode + ');\n' +
    'Meteor.startup(Template.body.renderToDocument);\n'
  );
}

/**
 * The webpack/rspack loader function.
 * Receives .jade source, returns JavaScript string.
 */
function meteorJadeLoader(this: LoaderContext, source: string): string {
  const compiler = getCompiler();
  const JadeCompiler = compiler.JadeCompiler;
  const SpacebarsCompiler = compiler.SpacebarsCompiler;
  const HTML = compiler.HTML;

  const resourcePath = this.resourcePath || '';
  const basename = path.basename(resourcePath);

  // Determine mode: .tpl.jade = template mode, .jade = file mode
  const isTemplateMode = basename.endsWith('.tpl.jade');
  const fileMode = !isTemplateMode;

  try {
    const result = JadeCompiler.parse(source, {
      filename: resourcePath,
      fileMode: fileMode,
    });

    let jsOutput = '';

    // Preamble: get Meteor globals
    jsOutput += '/* Generated by meteor-jade-loader from ' + basename + ' */\n';
    jsOutput += 'var Template = Package["templating-runtime"].Template;\n';
    jsOutput += 'var HTML = Package.htmljs.HTML;\n';
    jsOutput += 'var Blaze = Package.blaze.Blaze;\n';
    jsOutput += 'var Spacebars = Package.spacebars.Spacebars;\n';
    jsOutput += 'var Meteor = Package.meteor.Meteor;\n';
    jsOutput += '\n';

    if (fileMode) {
      // File mode: result has { head, body, bodyAttrs, templates }
      const fileResult = result as JadeFileResult;

      if (fileResult.head !== null) {
        // Head content is raw HTML that should be inserted into <head>.
        // In Rspack context, we skip head injection as it's typically
        // handled by the HTML plugin or Meteor's boilerplate.
        const headHTML = HTML.toHTML(fileResult.head);
        if (headHTML) {
          jsOutput += '// Head content (typically handled by Meteor boilerplate):\n';
          jsOutput += '// ' + headHTML.replace(/\n/g, '\n// ') + '\n\n';
        }
      }

      if (fileResult.body !== null) {
        const bodyRenderCode = SpacebarsCompiler.codeGen(fileResult.body, {
          isBody: true,
          sourceName: '<body>',
        });
        jsOutput += generateBodyJS(bodyRenderCode);
      }

      // Generate code for each template defined in the file
      const templateNames = Object.keys(fileResult.templates);
      for (let i = 0; i < templateNames.length; i++) {
        const tplName = templateNames[i];
        const tplTree = fileResult.templates[tplName];
        const renderFuncCode = SpacebarsCompiler.codeGen(tplTree, {
          isTemplate: true,
          sourceName: 'Template "' + tplName + '"',
        });
        jsOutput += generateTemplateJS(tplName, renderFuncCode);
      }
    } else {
      // Template mode (.tpl.jade): result is the compiled AST directly
      const templateName = path.basename(resourcePath, '.tpl.jade');
      const templateResult = result as HtmlContent;

      if (templateName === 'head') {
        const headHTML = HTML.toHTML(templateResult);
        if (headHTML) {
          jsOutput += '// Head content: ' + headHTML.replace(/\n/g, '\n// ') + '\n';
        }
      } else if (templateName === 'body') {
        const bodyRenderCode = SpacebarsCompiler.codeGen(templateResult, {
          isBody: true,
          sourceName: '<body>',
        });
        jsOutput += generateBodyJS(bodyRenderCode);
      } else {
        const renderFuncCode = SpacebarsCompiler.codeGen(templateResult, {
          isTemplate: true,
          sourceName: 'Template "' + templateName + '"',
        });
        jsOutput += generateTemplateJS(templateName, renderFuncCode);
      }
    }

    return jsOutput;

  } catch (err) {
    // Emit the error properly through webpack
    const error = new Error('Jade compilation error in ' + resourcePath + ': ' + err.message);
    error.stack = err.stack;
    this.emitError(error);
    // Return empty module to avoid build crash
    return '/* Jade compilation error: ' + err.message.replace(/\*\//g, '* /') + ' */\n';
  }
}

export = meteorJadeLoader;
